HPlusSportsWeb/Pages/Admin/Index.cshtml.cs
using HPlusSports.Shared.Models;

using HPlusSportsWeb.Pages.Extensions;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Newtonsoft.Json;

using System.Net.Http.Headers;

namespace HPlusSportsWeb.Pages.Admin
{
    public class IndexModel : PageModel
    {
        private readonly HttpClient _httpClient;

        public IndexModel(HttpClient httpClient)
        {
            _httpClient = httpClient;
        }

        [BindProperty]
        public ClothingProduct Cloth { get; set; }

        [BindProperty]
        public NutritionalProduct Nutrition { get; set; }

        public string ProgressMessage { get; set; }

        public async Task<IActionResult> OnPostCreateNewClothAsync()
        {
            var emptyCloth = new ClothingProduct();
            if (await TryUpdateModelAsync(
                emptyCloth,
                "cloth",
                c => c.Name, c => c.Description, c => c.Sizes))
            {
                var response = await _httpClient.PostAsJsonAsync("product/clothing", emptyCloth);

                if(response.IsSuccessStatusCode)
                {
                    var contentString = await response.Content.ReadAsStringAsync();
                    Cloth = JsonConvert.DeserializeObject<ClothingProduct>(contentString);
                    HttpContext.Session.SetObject(nameof(Cloth), Cloth);
                    ProgressMessage = "Clothing product Created";

                    return Page();
                }
                else
                {
                    throw new ApplicationException(response.ReasonPhrase);
                }
            }
            else
            {
                return BadRequest();
            }
        }

        public async Task<IActionResult> OnPostAddClothImageAsync(IFormFile imageFile)
        {
            var cloth = HttpContext.Session.GetObject<ClothingProduct>(nameof(Cloth));
            var result = await UplaodProductImage(imageFile, cloth);
            Cloth = result.Product;
            HttpContext.Session.SetObject(nameof(Cloth), Cloth);
            return result.ActionResult;
        }

        public async Task OnPostCreateNewNutritionAsync()
        {
            var emptyNutrition = new NutritionalProduct();
            if (await TryUpdateModelAsync(
                emptyNutrition,
                "Nutrition",
                c => c.Name, c => c.Description))
            {
                var response = await _httpClient.PostAsJsonAsync("product/nutrition", emptyNutrition);

                if (response.IsSuccessStatusCode)
                {
                    var contentString = await response.Content.ReadAsStringAsync();
                    Nutrition = JsonConvert.DeserializeObject<NutritionalProduct>(contentString);
                    HttpContext.Session.SetObject(nameof(Nutrition), Nutrition);
                    ProgressMessage = "Nutritional product Created";
                }
            }
        }

        public async Task<IActionResult> OnPostAddNutritionImageAsync(IFormFile imageFile)
        {
            var nutrition = HttpContext.Session.GetObject<NutritionalProduct>(nameof(Nutrition));
            var result = await UplaodProductImage(imageFile, nutrition);
            Nutrition = result.Product;
            HttpContext.Session.SetObject(nameof(Nutrition), Nutrition);
            return result.ActionResult;
        }

        private async Task<(IActionResult ActionResult, T Product)> UplaodProductImage<T>(IFormFile imageFile, T product) where T : ProductBase
        {
            if (imageFile.Length < 0)
            {
                return (BadRequest(), product);
            }

            var imageContent = new StreamContent(imageFile.OpenReadStream());
            imageContent.Headers.ContentDisposition = new ContentDispositionHeaderValue("form-data")
            {
                Name = "imageFile",
                FileName = imageFile.FileName
            };

            var putContent = new MultipartFormDataContent
            {
                { imageContent, "imageFile" }
            };

            var response = await _httpClient.PutAsync($"product/image/{product.Id}", putContent);
            if (!response.IsSuccessStatusCode)
            {
                throw new ApplicationException(response.ReasonPhrase);
            }

            var contentString = await response.Content.ReadAsStringAsync();
            product = JsonConvert.DeserializeObject<T>(contentString);
            ProgressMessage = "Image added";

            return (Page(), product);
        }
    }
}

HPlusSportsWeb/Pages/Admin/CreateClothing_Partial.cshtml
@model ClothingProduct
@using HPlusSports.Shared.Models

<section class="default">
<h4>ClothingProduct</h4>
<hr />
<div class="product-add">
    
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Sizes" class="control-label"></label>
                @Html.DropDownListFor(model => model.Sizes, Html.GetEnumSelectList<SizeType>(), new { @class = "form-control", multiple = "true", size = "5" })
                <span asp-validation-for="Sizes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" asp-page-handler="CreateNewCloth" class="btn btn-default" />
            </div>
        </form>

        <form enctype="multipart/form-data" method="post">
            <div class="form-group">
                <label for="ImageFile" class="control-label">Product Image:</label>
                <input type="file" id="imageFile" name="imageFile" class="form-control" required/>
            </div>
            <div class="form-group">
                <input type="submit" value="Add Image" asp-page-handler="AddClothImage" class="btn btn-default" />
            </div>
        </form>
</div>

 </section>

HPlusSportsWeb/Pages/Admin/CreateNutritional_Partial.cshtml
@model NutritionalProduct
@using HPlusSports.Shared.Models

<section class="default">
<h4>NutritionalProduct</h4>
<hr />
<div class="product-add">
    <form method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
        <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Create" asp-page-handler="CreateNewNutrition" class="btn btn-default" />
        </div>
    </form>

    <form enctype="multipart/form-data" method="post">
        <div class="form-group">
            <label for="ImageFile" class="control-label">Product Image:</label>
            <input type="file" id="imageFile" name="imageFile" class="form-control" required />
        </div>
        <div class="form-group">
            <input type="submit" value="Add Image" asp-page-handler="AddNutritionImage" class="btn btn-default" />
        </div>
    </form>
</div>
</section>

HPlusSportsWeb/Pages/Admin/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Create New Product";
}

<h2>Add a new product</h2>
<p class="text-info text-center">@Model.ProgressMessage</p>

<partial name="CreateClothing_Partial" for="Cloth"></partial>
<partial name="CreateNutritional_Partial" for="Nutrition"></partial>